import {
  nPrimary,
  neutrals,
  nSecondary,
  nRed,
  nNeutrals,
  primary,
} from '@afnexus/hummingbird-ui-assets';
import { MD3DarkTheme as DefaultTheme } from 'react-native-paper';

export const darkThemeColors = {
  ...DefaultTheme.colors,
  primary: nPrimary[400],
  primaryContainer: nPrimary[400],
  secondary: nPrimary[300],
  secondaryContainer: nPrimary[300],
  tertiary: nPrimary[200],
  tertiaryContainer: nPrimary[200],
  surface: nPrimary[900],
  surfaceVariant: nPrimary[300],
  surfaceDisabled: nPrimary[400],
  background: nPrimary[400],
  error: nPrimary[400],
  errorContainer: nPrimary[400],
  onPrimary: neutrals[900],
  onPrimaryContainer: neutrals[900],
  onSecondary: neutrals[900],
  onSecondaryContainer: neutrals[900],
  onTertiary: neutrals[900],
  onTertiaryContainer: neutrals[900],
  onSurface: neutrals[100],
  onSurfaceVariant: neutrals[100],
  onSurfaceDisabled: nPrimary[100],
  onError: neutrals[900],
  onErrorContainer: neutrals[400],
  onBackground: neutrals[400],
  outline: nPrimary[400],
  inverseSurface: nPrimary[400],
  inverseOnSurface: nPrimary[400],
  inversePrimary: nPrimary[400],
  backdrop: nPrimary[400],
  elevation: {
    level1: neutrals[800],
    level2: neutrals[700],
    level3: neutrals[600],
    level4: neutrals[500],
    level5: neutrals[500],
  },
};
